---
services:
  app:
    container_name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - $HOST_PORT_ADMIN:$CONTAINER_PORT_ADMIN
    volumes:
      - $HOST_VOLUME_PATH/data:/data
      - $HOST_VOLUME_PATH/letsencrypt:/etc/letsencrypt
networks:
  default:
    external: true
    name: nginx-proxy-manager
