---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TIMEZONE
    volumes:
      - $HOST_VOLUME_PATH/radarr:/config
      - $PLEX_MEDIA_PATH/movies:/movies
      - $HOST_VOLUME_PATH/downloads:/downloads
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TIMEZONE
    volumes:
      - $HOST_VOLUME_PATH/sonarr:/config
      - $PLEX_MEDIA_PATH/tv:/tv
      - $PLEX_MEDIA_PATH/anime:/anime
      - $HOST_VOLUME_PATH/downloads:/downloads
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TIMEZONE
    volumes:
      - $HOST_VOLUME_PATH/prowlarr:/config
    restart: unless-stopped

  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    container_name: seerr
    init: true
    user: $PUID:$PGID
    environment:
      - LOG_LEVEL=debug
      - TZ=$TIMEZONE
    volumes:
      - $HOST_VOLUME_PATH/seerr:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://seerr:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped

  rdt-client:
    image: rogerfar/rdtclient
    container_name: rdt-client
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TIMEZONE
    volumes:
      - $HOST_VOLUME_PATH/rdtclient:/data/db
      - $HOST_VOLUME_PATH/downloads:/data/downloads
    restart: unless-stopped

  # decypharr:
  #   image: cy01/blackhole:latest
  #   container_name: decypharr
  #   volumes:
  #     - /mnt/:/mnt:rshared
  #     -  $HOST_VOLUME_PATH/decypharr:/app
  #   restart: unless-stopped

  configarr:
    image: ghcr.io/raydak-labs/configarr
    container_name: configarr
    environment:
      - TZ=$TIMEZONE
    volumes:
      - $HOST_VOLUME_PATH/configarr/config:/app/config
      - $HOST_VOLUME_PATH/configarr/dockerrepos:/app/repos
      - $HOST_VOLUME_PATH/configarr/custom/cfs:/app/cfs
      - $HOST_VOLUME_PATH/configarr/custom/templates:/app/templates
    restart: on-failure

  flaresolverr-arr:
    image: ghcr.io/flaresolverr/flaresolverr
    container_name: flaresolverr-arr
    environment:
      - TZ=$TIMEZONE
    volumes:
      - $HOST_VOLUME_PATH/flaresolverr:/config
    restart: unless-stopped
networks:
  default:
    external: true
    name: nginx-proxy-manager