---
services:
  calibre:
    container_name: calibre
    image: ghcr.io/new-usemame/calibre-web-nextgen:latest
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$CALIBRE_TZ
    volumes:
      - $HOST_VOLUME_PATH/calibre/config:/config
      - $HOST_VOLUME_PATH/calibre/ingest:/cwa-book-ingest
      - $HOST_VOLUME_PATH/calibre/calibre-library:/calibre-library
      - $HOST_MEDIA_PATH/ebooks:/ebooks
    restart: unless-stopped
  audiobookshelf:
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:latest
    volumes:
      - $HOST_VOLUME_PATH/audiobookshelf/metadata:/metadata
      - $HOST_VOLUME_PATH/audiobookshelf/config:/config
      - $HOST_MEDIA_PATH/audiobooks:/audiobooks
    restart: unless-stopped
  shelfmark:
    container_name: shelfmark
    image: ghcr.io/calibrain/shelfmark:latest
    environment:
      - USE_BOOK_TITLE=true
      - TZ=$SHELFMARK_TZ
      - CWA_DB_PATH=/auth/app.db
      - PUID=$PUID
      - PGID=$PGID
    restart: unless-stopped
    volumes:
      - $HOST_VOLUME_PATH/shelfmark/config:/config
      - $HOST_DOWNLOAD_PATH:/downloads
      - $HOST_VOLUME_PATH/calibre/ingest:/books
      - $HOST_MEDIA_PATH/audiobooks:/audiobooks
      - $HOST_VOLUME_PATH/calibre/config/app.db:/auth/app.db:ro # Authentcation with CWA
  bookbridge:
    container_name: bookbridge
    image: ghcr.io/cporcellijr/bookbridge:latest
    restart: unless-stopped
    environment:
      - TZ=$BOOKDBRIDGE_TZ
      - ABS_TOKEN=$ABS_TOKEN
      - CWA_USERNAME=$CALIBRE_USER
      - CWA_PASSWORD=$CALIBRE_PASS
      - BOOKS_DIR=/ebooks
      - AUDIOBOOKS_DIR=/audiobooks
    volumes:
      - $HOST_VOLUME_PATH/bookbridge:/data
      - $HOST_VOLUME_PATH/calibre/calibre-library:/calibre-library
      - $HOST_MEDIA_PATH/ebooks:/ebooks
      - $HOST_MEDIA_PATH/audiobooks:/audiobooks
networks:
  default:
    external: true
    name: nginx-proxy-manager

