---
services:
  calibre:
    container_name: calibre
    image: crocodilestick/calibre-web-automated:latest
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TIMEZONE
    volumes:
      - $HOST_VOLUME_PATH/config:/config
      - $HOST_VOLUME_PATH/ingest:/cwa-book-ingest
      - $HOST_VOLUME_PATH/library:/calibre-library
    restart: unless-stopped
networks:
  default:
    external: true
    name: nginx-proxy-manager
