---
services:
  wings:
    container_name: pterodactyl-wings
    image: ghcr.io/pterodactyl/wings:latest
    restart: always
    networks:
      - wings0
    ports:
      - $HOST_PORT_DAEMON:$CONTAINER_PORT_DAEMON
      - $HOST_PORT_WINGS_SFTP:$CONTAINER_PORT_WINGS_SFTP
    tty: true
    environment:
      TZ: $TIMEZONE
      WINGS_UID: $WINGS_UID
      WINGS_GID: $WINGS_GID
      WINGS_USERNAME: $WINGS_USERNAME
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers/:/var/lib/docker/containers/
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - $HOST_VOLUME_PATH/etc/:/etc/pterodactyl/
      - $HOST_VOLUME_PATH/var/lib/:$HOST_VOLUME_PATH/var/lib/
      - $HOST_VOLUME_PATH/var/log/:$HOST_VOLUME_PATH/var/log/
      - $HOST_VOLUME_PATH/tmp/:$HOST_VOLUME_PATH/tmp/
networks:
  wings0:
    name: wings0
    driver: bridge
    ipam:
      config:
        - subnet: "172.21.0.0/16"
    driver_opts:
      com.docker.network.bridge.name: wings0
