---
services:
  shelfmark:
    container_name: shelfmark
    image: ghcr.io/calibrain/shelfmark:latest
    environment:
      - USE_BOOK_TITLE=true
      - TZ=$TIMEZONE
      - CWA_DB_PATH=/auth/app.db
      - PUID=$PUID
      - PGID=$PGID
    restart: unless-stopped
    volumes:
      - $CALIBRE_VOLUME_PATH/ingest:/books
      - $CALIBRE_VOLUME_PATH/config/app.db:/auth/app.db:ro # Authentcation with CWA
networks:
  default:
    external: true
    name: nginx-proxy-manager