---
services:
  shelfmark:
    container_name: stump
    image: aaronleopold/stump:latest
    restart: unless-stopped
    environment:
      - PUID=$PUID
      - PGID=$PGID
    volumes:
      - $HOST_VOLUME_PATH/config:/config
      - $HOST_VOLUME_PATH/data:/data
networks:
  default:
    external: true
    name: nginx-proxy-manager
